# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Java Selenium CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'    
        
    - name: setup Maven
      run: |
          wget -q https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          tar -xzf apache-maven-3.6.3-bin.tar.gz
          export PATH=$(pwd)/apache-maven-3.6.3/bin:$PATH 
          
    - name: setup chrome browser
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: 'latest'
   
    - name: check build environment
      run: |
          echo "java version"
          java -version

          echo "Maven version"
          mvn -version

          echo "chrome version"
          google-chrome --version

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' 
        
    - name: execute test
      run: mvn clean test -Pheadless-chrome,qa,smoke-test

    - name: archive test report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: reports

    
